# Generated by Django 5.2.8 on 2025-11-20 12:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('ACCEPTED', 'Accepted'), ('PROCESSING', 'Processing'), ('READY', 'Ready for Pickup/Delivery'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('requested_delivery_date', models.DateField(blank=True, help_text='When the consumer wants the goods.', null=True)),
                ('delivery_address', models.TextField(help_text='Snapshot of address at time of order')),
                ('notes', models.TextField(blank=True, help_text='Special instructions for Supplier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_sku', models.CharField(blank=True, max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Amount ordered (e.g., 5.5 kg)', max_digits=10)),
                ('unit', models.CharField(max_length=10)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price at the moment of purchase', max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
            ],
        ),
    ]
