# Generated by Django 5.2.8 on 2025-11-20 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierconsumerlink',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_links', to='users.consumerprofile'),
        ),
        migrations.AddField(
            model_name='supplierconsumerlink',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='The Supplier User who approved/rejected this link.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierconsumerlink',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumer_links', to='users.suppliercompany'),
        ),
        migrations.AlterUniqueTogether(
            name='supplierconsumerlink',
            unique_together={('supplier', 'consumer')},
        ),
    ]
