# Generated by Django 5.2.8 on 2025-11-20 12:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=20)),
                ('is_escalated', models.BooleanField(default=False, help_text='If True, requires Manager/Owner attention. Sales Reps can no longer resolve.')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, help_text='Text content of the message')),
                ('attachment', models.FileField(blank=True, help_text='Images, PDFs, or Audio files', null=True, upload_to='chat_attachments/')),
                ('is_audio', models.BooleanField(default=False, help_text='Frontend flag to render audio player')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.ForeignKey(help_text='Ensures message stays within the valid B2B relationship.', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='network.supplierconsumerlink')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
