# Generated by Django 5.2.8 on 2025-11-20 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0002_initial'),
        ('orders', '0002_initial'),
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='link',
            field=models.ForeignKey(help_text='The relationship context for this incident.', on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='network.supplierconsumerlink'),
        ),
        migrations.AddField(
            model_name='incident',
            name='order',
            field=models.ForeignKey(help_text='The specific order this complaint is about.', on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='orders.order'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.incident'),
        ),
    ]
