# Generated by Django 5.2.8 on 2025-11-20 12:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sku', models.CharField(blank=True, help_text='Stock Keeping Unit (Internal Code)', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('unit', models.CharField(choices=[('KG', 'Kilogram'), ('L', 'Liter'), ('PCS', 'Piece'), ('BOX', 'Box/Crate'), ('PACK', 'Pack'), ('G', 'Gram')], default='PCS', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per Unit in KZT', max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional discounted price', max_digits=10, null=True)),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_order_quantity', models.DecimalField(decimal_places=2, default=1, help_text='Minimum amount a consumer must buy', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='If False, hidden from catalog but kept for history.')),
                ('lead_time_days', models.PositiveIntegerField(default=1, help_text='Days required to prepare/ship this item.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
